version: '3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - 1433:1433
    volumes:
      - ./mssql:/var/opt/mssql
      - ./mssql:/docker-entrypoint-initdb.d