version: '3'
services:
  rushiwa_django:
    build: .
    container_name: rushiwa_django
    volumes:
      - ./:/code
      - ./applications:/applications
      - ./git:/git
    working_dir: /code
    ports:
      - 8000:8000
    expose:
      - 8000

    environment:
      - RUSHA_HOME=/code

    command: bash -c "
      ansible-playbook -i ansible/hosts.ini ansible/rushiwa_django_playbook.yml;
      python manage.py runserver 0.0.0.0:8000;" 

    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - 1433:1433
    volumes:
      - ./mssql:/var/opt/mssql
      - ./mssql:/docker-entrypoint-initdb.d

  rusha_nginx:
    image: nginx:latest
    container_name: rusha_nginx
    ports:
      - 80:80
    volumes:
      - ./static:/usr/share/nginx/html
      - ./nginx:/etc/nginx/nginx.conf.d
    depends_on:
      - rushiwa_django
  
  rusha_ui: 
    image: node:16
    container_name: rusha_ui
    ports: 
      - 3000:3000
    volumes: 
      - ../rusha-ui/:/src
    working_dir: /src
    
    depends_on:
      - rushiwa_django
    expose: 
      - 3000
    command: bash -c "npm install && npm start"

volumes:
  nginx:


 
      
    

    



  


    