version: '3'
services:
  rusha_django:
    build: .
    container_name: rusha_django
    volumes:
      - ./:/code
      - ./applications:/applications
      - ./git:/git
    working_dir: /code
    ports:
      - 8000:8000
    expose:
      - 8000

    environment:
      - RUSHA_HOME=/code

    command: bash -c "
      ansible-playbook -i ansible/hosts.ini ansible/rusha_django_playbook.yml;
      python manage.py runserver 0.0.0.0:8000;" 

    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - 1433:1433
    volumes:
      - ./mssql:/var/opt/mssql
      - ./mssql:/docker-entrypoint-initdb.d

  rusha_nginx:
    image: nginx:latest
    container_name: rusha_nginx
    ports:
      - 80:8001
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - rusha_django

 
      
    

    



  


    