# Generated by Django 4.0.8 on 2022-10-30 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rusha_applications_api', '0002_application_application_host_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applocation_domain',
            new_name='application_domain',
        ),
    ]
