# Generated by Django 4.0.8 on 2022-10-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rushiwa_applications_api', '0005_alter_application_application_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='application_domain',
        ),
        migrations.RemoveField(
            model_name='application',
            name='application_host',
        ),
        migrations.AddField(
            model_name='application',
            name='domain_name',
            field=models.CharField(default='a.localhost', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
