# Generated by Django 4.0.8 on 2022-10-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rushiwa_applications_api', '0008_remove_application_nginx_conf_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='proxy_host_name_and_or_port',
            field=models.CharField(default='http://localhost:8080', max_length=200),
        ),
    ]
