- hosts: digital_ocean_droplet_a
  vars:
    path: "{{ lookup('env', 'RUSHA_HOME')}}"
    remote_dest: "{{ lookup('env', 'RUSHA_REMOTE_DEST')}}"
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
    
    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
    
    - name: Install git
      become: true
      apt:
        name: git
        state: present

    - name: Install cron
      become: true
      apt:
        name: cron
        state: present
    
    - name: Enable cron
      become: true
      service:
        name: cron
        state: started
        enabled: yes

    - name: Copy current directory to remote
      synchronize:
        src: "{{ path }}"
        dest: "{{ remote_dest }}"
        recursive: yes
        delete: yes
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=.venv"
          - "--exclude=logs"
          - "--exclude=media"
          - "--exclude=static"
          - "--exclude=*.pyc"
          - "--exclude=*.sqlite3"
          - "--exclude=*.log"
          - "--exclude=*.pid"
          - "--exclude=*mssql*"

    - name: Set RUSHA_HOME environment variable
      become: true
      lineinfile:
        path: /etc/environment
        line: "RUSHA_HOME={{ remote_dest }}/rusha_django_project"
        state: present
        create: yes

    - name: Install python3
      become: true
      raw: apt install python3 -y && apt install python3-pip -y     

    - name: Add the Microsoft repository key to the list of trusted keys and add the Microsoft SQL Server Ubuntu repository
      become: true
      raw: 'curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
        && curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-release.list'

    - name: Update the sources list
      become: true
      raw: apt-get update

    - name: Install the SQL Server command-line tools
      become: true
      raw: ACCEPT_EULA=Y apt-get install -y msodbcsql17 mssql-tools18 unixodbc-dev


    - name: Add SQL Server tools to the path
      become: true
      raw: echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
       

    - name: Install poetry
      become: true
      pip:
        name: poetry
        state: present

    - name: Install dependencies
      become: true
      raw: cd "{{ remote_dest }}"/rusha_django_project && poetry export -f requirements.txt --without-hashes -o requirements.txt && pip3 install -r requirements.txt

    - name: run docker-compose
      become: true
      raw: docker-compose -f {{ remote_dest }}/rusha_django_project/docker-compose-dev.yml up -d --build    
   

    - name: Make cron file executable
      become: true
      file:
        path: "{{ remote_dest }}/rusha_django_project/dequeue_new_applications.py"
        mode: 0755
    
    - name: crontab entry for python app
      become: true
      cron:
        name: "python app"
        minute: "*/1"
        job: "{{remote_dest}}/rusha_django_project/dequeue_new_applications.py >> {{remote_dest}}/rusha_django_project/dequeue_new_applications_log_$(date +\\%Y\\%m\\%d).log 2>&1"

    - name: Checkout rusha-ui
      become: true
      git:
        repo: https://github.com/FAenX/rusha-ui.git
        dest: "{{ remote_dest }}/rusha_ui"
        version: master
        

    - name: run docker-compose
      become: true
      raw: docker-compose -f {{ remote_dest }}/rusha_django_project/docker-compose-dev.yml up -d    
   