- hosts: do
  vars:
    path: /home/manu/private/rusha_django
  tasks:
    - name: Mssql docker compose
      shell: docker-compose -f "{{path}}"/mssql.yml up -d

    - name: crontab entry for python app
      cron:
        name: "python app"
        minute: "*/1"
        job: "{{path}}/cron_jobs/dequeue_new_applications.py >> {{path}}/dequeue_new_applications_log_$(date +\\%Y\\%m\\%d\\%H).log 2>&1"
