- hosts: do
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
    - name: Install Python3.8
      apt:
        name: python3.8
        state: present
   